---
applications:
  traefik:
    options:
      routing_mode: path

  reductstore:
    charm: reductstore-k8s
    channel: edge
    trust: true
    resources:
      reductstore-image: reduct/store:latest
    scale: 1
    options:
      log-level: debug

  foxglove-studio:
    charm: foxglove-studio-k8s
    series: jammy
    channel: edge
    resources:
      foxglove-studio-image: ghcr.io/ubuntu-robotics/foxglove-studio:dev
    scale: 1
    options:
      server-port: 8080

  cos-registration-server:
    charm: cos-registration-server-k8s
    series: jammy
    channel: edge
    resources:
      cos-registration-server-image: cos-registration-server:local
    scale: 1
    storage:
      database: 1G
      
relations:
  - [reductstore:ingress, traefik:ingress]
  - [reductstore:catalogue, catalogue:catalogue]
  - [foxglove-studio:ingress, traefik:ingress]
  - [foxglove-studio:catalogue, catalogue:catalogue]
  - [cos-registration-server:ingress, traefik:ingress]
  - [cos-registration-server:catalogue, catalogue:catalogue]
  - [grafana:grafana-dashboard, cos-registration-server:grafana-dashboard]
  - [grafana:grafana-dashboard, cos-registration-server:grafana-dashboard-devices]
