/**/*:
  ros__parameters:
    storage: # local ReductStore instance
      url: "http://localhost:8383"
      api_token: "access_token"
      bucket: "ros_data"
      quota_type: "FIFO"
      quota_size: "200GB"
    pipelines:
      telemetry:
        filename_mode: "timestamp"
        include_topics:
          - "/camera/.*"
        exclude_topics:
          - "/camera/ignore"
        static_labels:
          source: telemetry
          robot: alpha
        split:
          max_duration_s: 3600
          max_size_bytes: 10000